name: test_splash
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  path_provider: ^2.1.5
  gap: ^3.0.1
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  skeletonizer: ^2.1.0+1
  dio: ^5.9.0
  curved_labeled_navigation_bar: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/appicon/playstore.png"
  image_path_ios: "assets/appicon/appstore.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/appicon/playstore.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/SVGs/
    - assets/covers/
    - assets/icons/
    - assets/appicon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
